### ISSUE TITLE
F you. :nerd_face: 

### ISSUE THREAD

**Issue by G9-dev-real** [BonziWorldz/BonziWorld-viruses#3]
YOU SKIDDED PEOPLES CODES! GO LEARN C++ OR C OR GDI. AND DO NOT STEAL PEOPLES CODES!

**Comment by G9-Dev-RealIsCool** [comment]
STOP SKIDDING MR BONZIWORLD

**Comment by DAriK8632** [comment]
skiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskiddedskidded

**Comment by G9-dev-real** [comment]
skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded skidded
